version: "3"

services:
  database:
    image: mongo
    container_name: mongo_test
    ports:
      - 27018:27018
    environment:
      MONGODB_DATABASE: ${DB_MONGODB_URI}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

